import { StyleSheet } from "react-native";

import { monoFont, palette } from "./theme";

const controlChrome = {
  backgroundColor: palette.raised,
  borderColor: palette.soft,
  borderRadius: 5,
  borderWidth: 1,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.canvas,
  },
  page: {
    padding: 16,
  },
  workoutPage: {
    padding: 12,
  },
  topActions: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 5,
    paddingHorizontal: 12,
    paddingTop: 4,
  },
  topActionButtons: {
    flexDirection: "row",
    gap: 5,
  },
  title: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 32,
    fontWeight: "800",
    marginBottom: 12,
  },
  workoutTitleInput: {
    ...controlChrome,
    color: palette.ink,
    flex: 1,
    fontFamily: monoFont,
    fontSize: 30,
    fontWeight: "800",
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  titleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  subtleTitle: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
  },
  mutedText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
  },
  metaText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 21,
  },
  timeInlineRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 1,
  },
  timeTextButton: {
    ...controlChrome,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  timeTextButtonText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 21,
  },
  errorText: {
    color: palette.danger,
    fontFamily: monoFont,
    fontSize: 16,
    marginVertical: 8,
  },
  centerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  rowHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  rowActions: {
    flexDirection: "row",
    gap: 5,
  },
  flexColumn: {
    flex: 1,
  },
  flexSpacer: {
    flex: 1,
  },
  historyRow: {
    paddingVertical: 10,
    gap: 5,
  },
  historyTitle: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 22,
    fontWeight: "800",
  },
  historySummary: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 22,
  },
  historySummaryRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  historySummaryName: {
    color: palette.muted,
    flexShrink: 1,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 22,
    minWidth: 82,
  },
  historySummarySets: {
    color: palette.ink,
    flex: 1,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 22,
  },
  iconButton: {
    ...controlChrome,
    alignItems: "center",
    height: 30,
    justifyContent: "center",
    paddingHorizontal: 0,
    width: 30,
  },
  iconButtonText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 20,
  },
  iconButtonSmall: {
    ...controlChrome,
    alignItems: "center",
    height: 30,
    justifyContent: "center",
    paddingHorizontal: 0,
    width: 30,
  },
  iconButtonActive: {
    backgroundColor: palette.softStrong,
    borderColor: palette.active,
  },
  iconButtonDisabled: {
    opacity: 0.45,
  },
  historyIconButton: {
    width: 30,
  },
  iconButtonTiny: {
    ...controlChrome,
    alignItems: "center",
    height: 30,
    width: 30,
    justifyContent: "center",
    paddingHorizontal: 0,
  },
  timerButton: {
    ...controlChrome,
    alignItems: "center",
    height: 30,
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  timerButtonText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 16,
  },
  iconButtonTextSmall: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
  },
  textButton: {
    ...controlChrome,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  textButtonText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 16,
  },
  recoverySheetSafeArea: {
    justifyContent: "flex-end",
    width: "100%",
  },
  recoverySheet: {
    backgroundColor: palette.canvas,
    borderColor: palette.line,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderWidth: 1,
    gap: 7,
    padding: 12,
  },
  recoveryActions: {
    flexDirection: "row",
    gap: 7,
    marginTop: 5,
  },
  inlineEditRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  inlineInput: {
    ...controlChrome,
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 18,
    minWidth: 66,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  bodyWeightInputBox: {
    ...controlChrome,
    alignItems: "center",
    flexShrink: 0,
    flexDirection: "row",
    minHeight: 28,
    paddingHorizontal: 5,
  },
  bodyWeightInput: {
    color: palette.ink,
    flexShrink: 0,
    fontFamily: monoFont,
    fontSize: 18,
    paddingHorizontal: 0,
    paddingVertical: 2,
  },
  bodyWeightUnit: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 20,
    paddingLeft: 2,
  },
  planBlock: {
    marginTop: 18,
    gap: 6,
  },
  planHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    alignSelf: "stretch",
    minHeight: 28,
  },
  planRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
  },
  planRowDragging: {
    backgroundColor: palette.soft,
    borderRadius: 5,
    zIndex: 2,
  },
  dragHandle: {
    alignItems: "center",
    borderRadius: 5,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  dragHandleActive: {
    backgroundColor: palette.softStrong,
  },
  planName: {
    color: palette.ink,
    flex: 1,
    fontFamily: monoFont,
    fontSize: 17,
  },
  microButton: {
    alignItems: "center",
    borderColor: palette.line,
    borderRadius: 5,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    paddingHorizontal: 0,
    paddingVertical: 0,
    width: 32,
  },
  microButtonText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 14,
  },
  addExerciseRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 5,
  },
  exerciseInput: {
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 5,
    color: palette.ink,
    flex: 1,
    fontFamily: monoFont,
    fontSize: 18,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  exerciseSuggestions: {
    gap: 1,
    marginTop: 2,
  },
  exerciseSuggestion: {
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  exerciseSuggestionText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 17,
    lineHeight: 22,
  },
  exerciseSuggestionMutedText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 17,
    lineHeight: 22,
  },
  addButton: {
    alignItems: "center",
    borderColor: palette.line,
    borderRadius: 5,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    paddingHorizontal: 0,
    width: 32,
  },
  exerciseBlock: {
    marginTop: 24,
    gap: 4,
  },
  exerciseTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
  },
  exerciseTitleActions: {
    flexDirection: "row",
    flexShrink: 0,
    gap: 5,
  },
  exerciseTitle: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 27,
    fontWeight: "800",
  },
  noteBadgeSelf: {
    alignSelf: "flex-start",
  },
  noteBadge: {
    alignSelf: "flex-start",
    backgroundColor: palette.soft,
    borderRadius: 5,
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 21,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  noteBadgeRow: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: palette.soft,
    borderRadius: 5,
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  noteBadgeText: {
    backgroundColor: palette.soft,
    borderRadius: 5,
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 21,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  noteBadgeTextInline: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 16,
    lineHeight: 21,
  },
  historyScroller: {
    marginTop: 4,
  },
  historyScrollerContent: {
    alignItems: "flex-start",
  },
  historyBox: {
    borderColor: palette.line,
    borderRadius: 7,
    borderWidth: 1,
    gap: 3,
    padding: 7,
  },
  historyChartBlock: {
    gap: 1,
  },
  historyChart: {
    position: "relative",
    width: "100%",
  },
  historyChartLine: {
    backgroundColor: palette.muted,
    height: 1.5,
    position: "absolute",
    transformOrigin: "left center",
  },
  historyChartDot: {
    backgroundColor: palette.muted,
    borderRadius: 3,
    height: 5,
    position: "absolute",
    width: 5,
  },
  historyChartValue: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 11,
    position: "absolute",
    textAlign: "center",
    width: 56,
  },
  statLine: {
    flexDirection: "row",
    gap: 8,
  },
  statLabel: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
    width: 74,
  },
  statValue: {
    color: palette.ink,
    flex: 1,
    fontFamily: monoFont,
    fontSize: 16,
  },
  currentSetHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  setGroup: {
    gap: 2,
    marginTop: 4,
  },
  setLine: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  inlineSetChip: {
    ...controlChrome,
    backgroundColor: "transparent",
    paddingHorizontal: 2,
    paddingVertical: 1,
  },
  inlineSetChipActive: {
    borderColor: palette.active,
    borderWidth: 1.5,
    backgroundColor: palette.soft,
  },
  inlineSetText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 21,
  },
  warmupInlinePrefix: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 21,
    marginRight: 2,
  },
  separatorChip: {
    ...controlChrome,
    backgroundColor: "transparent",
    marginHorizontal: 1,
    paddingHorizontal: 2,
    paddingVertical: 1,
  },
  separatorText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 21,
    minWidth: 6,
    paddingLeft: 0,
    paddingRight: 0,
  },
  supText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 11,
    lineHeight: 11,
  },
  noteList: {
    gap: 3,
    marginTop: 3,
  },
  noteRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
  },
  noteLetter: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 13,
    fontWeight: "800",
    minWidth: 14,
    textAlign: "center",
  },
  modalShade: {
    backgroundColor: "rgba(31, 28, 23, 0.54)",
    flex: 1,
    justifyContent: "flex-end",
  },
  dismissibleModalContent: {
    width: "100%",
  },
  keyboardAvoidingModalContent: {
    flex: 1,
    justifyContent: "flex-end",
    width: "100%",
  },
  nativeKeyboardBackgroundFill: {
    backgroundColor: palette.canvas,
    left: -1,
    position: "absolute",
    right: -1,
  },
  keyboardDock: {
    backgroundColor: palette.canvas,
    maxHeight: "92%",
    width: "100%",
  },
  sheetDock: {
    backgroundColor: palette.canvas,
    width: "100%",
  },
  keyboardSheet: {
    backgroundColor: palette.canvas,
    borderColor: palette.line,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingTop: 8,
    paddingBottom: 6,
    position: "relative",
  },
  keyboardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  editorValueRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    marginTop: 2,
  },
  valueChip: {
    ...controlChrome,
    backgroundColor: "transparent",
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  bigValueText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 22,
  },
  keypad: {
    gap: 4,
    marginTop: 7,
  },
  keypadRow: {
    flexDirection: "row",
    gap: 4,
    height: 43,
  },
  keypadSplitCell: {
    flex: 1,
    flexDirection: "row",
    gap: 4,
  },
  keyIconPair: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
  },
  key: {
    ...controlChrome,
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    minWidth: 0,
  },
  keyBlank: {
    flex: 1,
  },
  keySmall: {
    ...controlChrome,
    alignItems: "center",
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  keyActive: {
    backgroundColor: palette.softStrong,
    borderColor: palette.active,
  },
  keyDisabled: {
    opacity: 0.35,
  },
  keyDark: {
    backgroundColor: palette.active,
    borderColor: palette.active,
  },
  keyText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 18,
  },
  keyDarkText: {
    color: palette.raised,
    fontFamily: monoFont,
    fontSize: 18,
  },
  helperShade: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    backgroundColor: "rgba(31, 28, 23, 0.62)",
    justifyContent: "center",
    padding: 14,
  },
  helperDialog: {
    backgroundColor: palette.canvas,
    borderColor: palette.line,
    borderRadius: 7,
    borderWidth: 1,
    gap: 9,
    maxHeight: "88%",
    padding: 10,
    width: "100%",
  },
  helperHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  helperTitle: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 22,
  },
  helperDoneButton: {
    ...controlChrome,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 30,
    paddingHorizontal: 5,
  },
  helperDoneText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 15,
  },
  helperDoneFooter: {
    ...controlChrome,
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "center",
    minHeight: 30,
  },
  helperDoneFooterText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 16,
  },
  helperSection: {
    gap: 4,
  },
  helperLargeText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 19,
    lineHeight: 24,
  },
  helperUnit: {
    color: palette.muted,
    fontSize: 14,
  },
  segmentedRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
  },
  segmentedButton: {
    ...controlChrome,
    justifyContent: "center",
    minHeight: 30,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  segmentedButtonActive: {
    backgroundColor: palette.softStrong,
    borderColor: palette.active,
  },
  segmentedButtonText: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
  },
  segmentedButtonTextActive: {
    color: palette.ink,
  },
  addWeightRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
  },
  addWeightValue: {
    backgroundColor: palette.raised,
    borderColor: palette.soft,
    borderRadius: 5,
    borderWidth: 1,
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 21,
    minWidth: 86,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  addWeightButtons: {
    gap: 3,
  },
  addWeightStepButton: {
    alignItems: "center",
    backgroundColor: palette.raised,
    borderColor: palette.line,
    borderRadius: 5,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  addWeightStepText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 20,
    lineHeight: 22,
  },
  helperMutedLine: {
    color: palette.muted,
    flexShrink: 1,
    fontFamily: monoFont,
    fontSize: 15,
    lineHeight: 20,
  },
  suggestionBlock: {
    gap: 1,
  },
  suggestionRow: {
    alignItems: "center",
    borderColor: "transparent",
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingVertical: 3,
  },
  suggestionRowActive: {
    backgroundColor: palette.softStrong,
    borderColor: palette.active,
    paddingHorizontal: 7,
  },
  suggestionText: {
    color: palette.ink,
    flex: 1,
    fontFamily: monoFont,
    fontSize: 14,
    lineHeight: 18,
  },
  useButton: {
    ...controlChrome,
    alignItems: "center",
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  plateTopRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  helperSelect: {
    ...controlChrome,
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    minHeight: 30,
    paddingHorizontal: 5,
  },
  helperSelectText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 17,
  },
  helperMenu: {
    alignSelf: "flex-start",
    backgroundColor: palette.raised,
    borderColor: palette.line,
    borderRadius: 7,
    borderWidth: 1,
    overflow: "hidden",
    width: 180,
  },
  helperMenuItem: {
    borderBottomColor: palette.soft,
    borderBottomWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  helperMenuItemText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 17,
  },
  helperLine: {
    flexDirection: "row",
    gap: 12,
  },
  helperLineLeft: {
    color: palette.muted,
    fontFamily: monoFont,
    fontSize: 16,
    width: 48,
  },
  helperLineRight: {
    color: palette.ink,
    flex: 1,
    fontFamily: monoFont,
    fontSize: 16,
  },
  platePlan: {
    gap: 7,
  },
  plateVisualRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    minHeight: 70,
  },
  barVisual: {
    alignItems: "center",
    backgroundColor: "#b9c0cc",
    borderColor: "#7f8793",
    borderRadius: 4,
    borderWidth: 1,
    height: 16,
    justifyContent: "center",
    minWidth: 128,
  },
  barVisualText: {
    color: palette.active,
    fontFamily: monoFont,
    fontSize: 12,
    fontWeight: "800",
  },
  plateBlockRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 3,
  },
  plateBlock: {
    alignItems: "center",
    borderRadius: 3,
    borderWidth: 1,
    justifyContent: "center",
    width: 14,
  },
  plateBlockText: {
    fontFamily: monoFont,
    fontSize: 8,
    transform: [{ rotate: "-90deg" }],
  },
  plateLegendRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 2,
  },
  plateLegendItem: {
    alignItems: "center",
    gap: 2,
  },
  plateChip: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  plateChipText: {
    fontFamily: monoFont,
    fontSize: 10,
  },
  plateCountText: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 13,
    lineHeight: 14,
  },
  noteSheet: {
    backgroundColor: palette.canvas,
    borderColor: palette.line,
    borderWidth: 1,
    padding: 12,
    position: "relative",
  },
  noteInput: {
    ...controlChrome,
    backgroundColor: "transparent",
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 18,
    minHeight: 132,
    padding: 6,
    textAlignVertical: "top",
  },
  timeEditorInput: {
    ...controlChrome,
    backgroundColor: "transparent",
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 24,
    minHeight: 48,
    paddingHorizontal: 5,
    paddingVertical: 3,
  },
  dateTimePicker: {
    alignSelf: "stretch",
  },
  noteActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  sheetActionsEnd: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  sheetActionFill: {
    flex: 1,
  },
  primaryWideButton: {
    backgroundColor: palette.active,
    flex: 1,
  },
  primaryWideButtonText: {
    color: palette.raised,
    fontFamily: monoFont,
    fontSize: 18,
  },
  previewBox: {
    backgroundColor: palette.canvas,
    borderColor: palette.line,
    borderRadius: 7,
    borderWidth: 1,
    margin: 16,
    maxHeight: "88%",
    padding: 14,
  },
  previewScroll: {
    marginTop: 10,
  },
  previewExercise: {
    marginBottom: 12,
  },
  previewExerciseTitle: {
    color: palette.ink,
    fontFamily: monoFont,
    fontSize: 20,
    fontWeight: "800",
  },
});
